apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  namespace: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: python-app
        image: ravindra806/versionapp:76
        ports:
        - containerPort: 5000
        imagePullPolicy: Always